# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

# from PySide2 import QtGui, QtWidgets

# def hide_show():
#     x.setVisible(not x.isVisible()) # toggles visibility of the label
#     w.adjustSize() # adjusts size of widget

# app = QtWidgets.QApplication([])

# w = QtWidgets.QWidget()
# l = QtWidgets.QVBoxLayout(w)
# b = QtWidgets.QPushButton('Click me')
# l.addWidget(b)
# x = QtWidgets.QLabel('Some Text')
# l.addWidget(x)
# b.clicked.connect(hide_show)
# w.show()

# app.exec_()

from PySide2 import QtGui, QtWidgets

def hide_show():
    x.setVisible(not x.isVisible()) # toggles visibility of the label
    w2.adjustSize() # adjusts size of widget
    w.adjustSize() # adjusts size of main window

app = QtWidgets.QApplication([])

w = QtWidgets.QMainWindow()
w2 = QtWidgets.QWidget()
l = QtWidgets.QVBoxLayout(w2)
b = QtWidgets.QPushButton('Click me')
l.addWidget(b)
x = QtWidgets.QTextEdit('Some Text')
l.addWidget(x)
b.clicked.connect(hide_show)
w.setCentralWidget(w2)
w.show()

app.exec_()